#!/bin/bash

#file="$(dirname -- "$(readlink -f "${BASH_SOURCE}")")/links.txt"
folder="$HOME/.config/lnkr"
filename="links"
file="$folder/$filename"

# Create file with links
if [[ ! -d $folder ]]
then
    mkdir -p $folder
fi

if [[ ! -f $file ]]
then
    touch $file
    echo https://github.com/naelxd/lnkr > $file
fi

# Main functional
if [ $# == 0 ]
then
    i=1
    links=()

    echo "--------------- Saved Links ---------------"

    while read -r line; do
        if [ "$line" != "" ]; then
            echo "$i - $line"
            links+=("$line")
            let i++
        fi
    done <$file

    read -p "Open link number... " n
    python -mwebbrowser ${links[n]} 
elif [ $# == 1 ]
then
    if [ $1 == "-h" ]
    then
        echo "Usage:
lnkr - open link
lnkr[option] - use option 

Options:
    [-w] Write new link
    [-w][link] Write link in filename
    [-d] Delete link"
    elif [ $1 == "-w" ]
    then
        "${EDITOR:-vim}" $file
    elif [ $1 == "-d" ]
    then
        i=1
        links=()

        echo "--------------- Saved Links ---------------"

        while read -r line; do
            if [ "$line" != "" ]; then
                echo "$i - $line"
                links+=("$line")
                let i++
            fi
        done <$file

        read -p "Delete link number... " n
        sed -i $n"d" $file
    else
        echo "lnkr -h To help" 
    fi
elif [ $# == 2 ]
then
    if [ $1 == "-w" ]
    then
        echo $2 >> $file
    else
        echo "lnkr -h To help"
    fi
else
    echo "lnkr -h To help"
fi
